### PR TITLE
Update binary to make it exit with 0 or 1

### PR DESCRIPTION
**Pull request by lucascaton**

### CODE REVIEW

**Comment by zenspider** [comment]
I'm not sure I agree that having flay output something means it should exit non-zero. For example, should you hook this into your CI on your project... should it really say that you failed a PR because flay detects similar code?

**Comment by lucascaton** [comment]
Hi @zenspider! By using a tool like [massa](https://github.com/lucascaton/massa/blob/master/config/default_tools.yml#L4), you can specify if your build should or should not fail if a particular tool exits with 1. 😄

**Comment by zenspider** [comment]
To start... I'm not against this PR. I just want to understand why you would possibly want it first.

Right. That doesn't address my question at all. Let's say you use massa (horribly cringy name?) on your CI. Let's say that you wrote some code that you consider good... say, minitest. 😀

When flay comes back with something like this:

https://codeclimate.com/github/seattlerb/minitest/Minitest::Assertions#duplication

it should fail? Should you really do the extra work to make unclear code (eg, lots of metaprogramming) just to get flay to not find anything?

The point of flay is to make humans see things they might not have seen on their own and to _think about it_. It is *not* a tool that says "this is bad".

**Comment by zenspider** [comment]
I ask for understanding and you close and delete the branch?

**Comment by gizotti** [comment]
@zenspider I know the issue was closed, but I think both have good point.

We don't use flay in our team(mainly because it's the first time I hear about the gem), but we fail any build where `rubocop` or `eslint` fails.
Since this is not a behaviour everybody wants, couldn't we make the return of 0 and 1 optional via a config variable? This way we can make the default behaviour to always return `nil` as it is right now, but if someone really wants to fail they just need to setup `flay` to do so.

**Comment by Nakilon** [comment]
AFAIK, RSpec also return 1 if "there was smth bad", so I just put `set +e` `set -e` around in the bash CI step.

**Pull request closed without merging**
