### PR TITLE
Report to contain violation line range

### PR DESCRIPTION
**Pull request by marcinwyszynski**

### CODE REVIEW

**Comment by zenspider** [comment]
Can you remove your reformatting so the diff is functional only?

**Comment by zenspider** [comment]
(feel free to send a second PR to normalize formatting--tho I'll reject un-aligning `=` lines)

**Comment by marcinwyszynski** [comment]
Fair enough, my bad. PTAL.

**Comment by zenspider** [comment]
Why did you close this and the flog ticket you opened?

**Comment by marcinwyszynski** [comment]
I was cleaning up my pull requests and decided that a month of silence was enough to give up.

**Comment by zenspider** [comment]
Uh. OK. Sorry I didn't jump when you said jump.

**Comment by marcinwyszynski** [comment]
Judging by the passive aggressive tone of your reply I can only assume I've offended you. Which totally wasn't my intention - I just like to keep my PR queue clean as I use Github for work, too. I hope that you can appreciate other folks contributing on their own terms, strange as they may seem to you.

**Pull request closed without merging**
