### PR TITLE
Resolve issue of attempting to modify frozen string

### PR DESCRIPTION
**Pull request by alanjackson**

### CODE REVIEW

**Comment by alanjackson** [comment]
We are seeing the following exception being generated:
/Users/alan.jackson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/flay-2.6.0/lib/flay.rb:138:in `[]=': can't modify frozen String (RuntimeError)
	from /Users/alan.jackson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/flay-2.6.0/lib/flay.rb:138:in `block in expand_dirs_to_files'
	from /Users/alan.jackson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/flay-2.6.0/lib/flay.rb:138:in `map'
	from /Users/alan.jackson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/flay-2.6.0/lib/flay.rb:138:in `expand_dirs_to_files'
	from /Users/alan.jackson/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/flay-2.6.0/bin/flay:7:in `<top (required)>'
	from /Users/alan.jackson/.rbenv/versions/2.1.3/bin/flay:23:in `load'
	from /Users/alan.jackson/.rbenv/versions/2.1.3/bin/flay:23:in `<main>'
	from /Users/alan.jackson/.rbenv/versions/2.1.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/alan.jackson/.rbenv/versions/2.1.3/bin/ruby_executable_hooks:15:in `<main>'

the dirs variable contains this:
["./lib/zamenhof/builder.rb",
 "./lib/zamenhof/factory.rb",
 "./lib/zamenhof/node.rb",
 "./lib/zamenhof/reader.rb",
 "./lib/zamenhof/tree.rb",
 "./lib/zamenhof/tree_configuration.rb",
 "./lib/zamenhof/utils.rb",
 "./lib/zamenhof/version.rb",
 "./lib/zamenhof.rb"]

I have been unable to run your tests as I can't see how to do that!
I presume you are happy to accept contributions...

**Comment by zenspider** [comment]
This is fixed. Thanks!

**Comment by rhardih** [comment]
This is still broken the latest version.

````bash
rene $ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin13.0]
[~/Code] (master)
rene $ gem search flay --local

*** LOCAL GEMS ***

flay (2.6.0)
flay-js (0.0.3)
[~/Code] (master)
rene $ flay -v foo.rb
/Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/flay-2.6.0/lib/flay.rb:137:in `[]=': can't modify frozen String (RuntimeError)
        from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/flay-2.6.0/lib/flay.rb:137:in `block in expand_dirs_to_files'
        from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/flay-2.6.0/lib/flay.rb:137:in `map'
        from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/flay-2.6.0/lib/flay.rb:137:in `expand_dirs_to_files'
        from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/flay-2.6.0/bin/flay:7:in `<top (required)>'
        from /Users/rene/.rbenv/versions/2.1.5/bin/flay:23:in `load'
        from /Users/rene/.rbenv/versions/2.1.5/bin/flay:23:in `<main>'
[~/Code] (master)
`````

**Comment by rhardih** [comment]
Seems fixed on master though. Forgot to cut a new release on rubygems?

````bash
[~/Code/flay] (master)
rene $ gem install pkg/flay-2.6.0.gem
Successfully installed flay-2.6.0
1 gem installed
[~/Code/flay] (master)
rene $ flay -v foo.rb
Processing foo.rb
Total score (lower is better) = 0
````

**Comment by alanjackson** [comment]
As far as I can see, a new version has not been pushed to RubyGems.

2.6.0 introduced the problem, I presume 2.7.0 will resolve the problem - once made available

Currently, we have fixed our version back to 2.5.0

Regards
Alan

**Pull request closed without merging**
